PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Se vedi BACCHE nel terreno,\n"
	.string "raccoglile pure senza problemi.\p"
	.string "Ma ricorda di piantarne sempre\n"
	.string "una nello stesso punto!\p"
	.string "Tieni, CAMPIONE, prendi questa\n"
	.string "BACCHACHESTA per il viaggio!$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Da come ti muovi, sei un vero\n"
	.string "esperto con i tuoi POKéMON!\p"
	.string "Gli ALLENATORI fanno tenere spesso\n"
	.string "le BACCHE ai loro POKéMON.\p"
	.string "Salva la tua mamma, mi raccomando!$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I'm going to try really hard and make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "You should try the BERRY CRUSH\n"
	.string "machine with your friends.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Which BERRY should be planted?\n"
	.string "Should you use or hoard BERRIES?\p"
	.string "It's fun to think about.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_YesYouUnderstand:
	.string "Yes, yes.\n"
	.string "You understand what I mean.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… But it is important to make your\n"
	.string "own impressions, I guess…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I think that BERRY is rare.\n"
	.string "I hope you raise it with loving care.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "I'll get more BERRIES from\n"
	.string "the BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When it gets right down to it…\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "When it gets right down to it…\p"
	.string "It's because you're a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "When it gets right down to it…\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Be sure to visit the PRETTY PETAL\n"
	.string "flower shop near RUSTBORO.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Ciao!\p"
	.string "Questo è il negozio FIORISTA!\n"
	.string "Diffondiamo fiori nel mondo!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vorresti sapere\n"
	.string "qualcosa di più sulle BACCHE?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Come ti chiami?\p"
	.string "{PLAYER}{KUN}?\n"
	.string "È davvero un bel nome!\p"
	.string "{PLAYER}{KUN}, vorresti sapere\n"
	.string "qualcosa di più sulle BACCHE?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Le BACCHE crescono su alberi che\n"
	.string "prosperano nel terreno soffice.\p"
	.string "Se raccogli delle BACCHE,\n"
	.string "piantane sempre una nella terra!\p"
	.string "La BACCA germoglierà presto,\n"
	.string "fiorirà splendidamente e darà\l"
	.string "altre BACCHE saporite.\p"
	.string "Vorrei vedere il mondo intero\n"
	.string "pieno di fiori meravigliosi!\l"
	.string "Questo è il mio grande sogno.\p"
	.string "Aiutaci anche tu, {PLAYER}{KUN}!\n"
	.string "Pianta le BACCHE nel mondo!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "I fiori portano tanta felicità a\n"
	.string "tutti, non trovi anche tu?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Ciao, CAMPIONE!\p"
	.string "Più cure doni ai tuoi fiori,\n"
	.string "più sbocceranno rigogliosi!\p"
	.string "So che stai cercando tua madre…\n"
	.string "Voglio darti una mano anch'io!\p"
	.string "Prendi questo VASO WAILMER!$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mentre le piantine crescono,\n"
	.string "annaffiale con il VASO WAILMER.\p"
	.string "Oh, e un'altra cosa importante!\p"
	.string "Se non raccogli le BACCHE,\n"
	.string "cadranno per terra ma poi\l"
	.string "germoglieranno di nuovo da sole.\p"
	.string "Non è fantastico? Hanno una vera\n"
	.string "e propria voglia di vivere!$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Voglio essere come le mie sorelle!\n"
	.string "Coltivo anch'io tanti bei fiori!\p"
	.string "Tieni, CAMPIONE!\n"
	.string "Questa BACCA è per te!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Puoi piantare una BACCA o darla\n"
	.string "da tenere a un tuo POKéMON.\p"
	.string "C'è una macchina che le frulla\n"
	.string "per creare buone CARAMELLE!\p"
	.string "Ne vorrei tanto una anch'io!$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hi, what's your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so\n"
	.string "I would grow healthy and warmhearted.\l"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI will give you this BERRY, too!\n"
	.string "I really like it lots!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "I wonder what kind of wish is included\n"
	.string "in your name.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you like\n"
	.string "the spring, and if you're born in the\l"
	.string "summer, do you like the summer?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Then KIRI was born in the autumn,\n"
	.string "so I love the autumn!\p"
	.string "Which season do you like?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "It doesn't matter…\p"
	.string "There's so much that I want to know…$"
