gText_Birch_Welcome::
	.string "Ehilà! Ti stavo aspettando!\p"
	.string "Bentornato nella terra di HOENN!\p"
	.string "Il mio nome è BIRCH.\p"
	.string "Ma per tutti sono il\n"
	.string "PROFESSOR POKéMON!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Questo è quello che chiamiamo\n"
	.string "“POKéMON”.{PAUSE 96}\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Dopo la tua grande vittoria\n"
	.string "alla LEGA POKéMON, eccoti qui!\p"
	.string "Il nostro mondo è popolato da\n"
	.string "queste straordinarie creature.\p"
	.string "Condividiamo con loro ogni cosa:\n"
	.string "amicizia, lavoro e battaglie.\p"
	.string "Eppure, anche per un CAMPIONE,\n"
	.string "i misteri sui POKéMON non\l"
	.string "finiscono mai!\p"
	.string "Ecco perché continuo a studiarli\n"
	.string "nel mio laboratorio di ricerca.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E tu chi sei?$"

gText_Birch_BoyOrGirl::
	.string "Sei un ragazzo?\n"
	.string "O sei una ragazza?$"

gText_Birch_WhatsYourName::
	.string "Perfetto.\n"
	.string "Qual è il tuo nome?$"

gText_Birch_SoItsPlayer::
	.string "Quindi ti chiami {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, ma certo!\p"
	.string "Tu sei {PLAYER}{KUN}!\n"
	.string "Il nostro celebre CAMPIONE!\p"
	.string "Tua madre ad ALISOPOLI non sta\n"
	.string "più nella pelle per il tuo arrivo!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bene, sei pronto?\p"
	.string "Il tuo rientro a casa sta\n"
	.string "per compiersi!\p"
	.string "Scendi dal furgoncino: tua madre\n"
	.string "ti aspetta a braccia aperte!\p"
	.string "Ti aspetto più tardi al mio\n"
	.string "LABORATORIO POKéMON!\p"
	.string "$"
